### ISSUE TITLE
Switching button profile breaks button functionality

### ISSUE THREAD

**Issue by finaltransmit** [jrbudda/Vivecraft_110#38] opened 2016-07-31 18:16 UTC
Switching button profile while in game causes no buttons except the menu button to have any effect. This is not fixed until the game is restarted.

**Comment by jrbudda** [comment] 2016-07-31 19:31
Do you mean the VR Profiles? yea those don't work see https://github.com/jrbudda/minecrift/issues/69

**Comment by finaltransmit** [comment] 2016-07-31 21:13
For me they seem to work fine if i restart minecraft

**Comment by jrbudda** [comment] 2016-12-02 15:54
Duplicate of https://github.com/jrbudda/minecrift/issues/69

**Closed by jrbudda** 2016-12-02 15:54 UTC
