### ISSUE TITLE
Getting double vision on vive

### ISSUE THREAD

**Issue by wristsoffury** [jrbudda/Vivecraft_110#71] opened 2016-10-13 21:22 UTC
Hi,

Was looking forward to playing vivecraft and the setup was simple, however... when i'm in game, its as though each eye is too far apart and im getting double vision.  The IPD setting on the vive doesnt fix it.. has anyone else come across this?

I've tried altering numerous settings from the display menu but nothing that brings the two images together.

Hope this can be resolved,
Thanks

**Comment by jrbudda** [comment] 2016-10-13 21:52
I've gotten reports of this.. it was caused by a steamVR update and I don't think it's something I can fix on my end. I've submitted a ticket to Valve but I have no personally been able to reproduce the problem.

**Comment by THEHCKEABLE** [comment] 2016-11-22 06:18
This seems to be fixed with the most recent SteamVR update. It's working great as far as I can tell. 
Wish there was forge mod support but I understand why there isn't for the time being.

Is there a way you can package optifine apart from this so we can update it manually? Or do you have to make some changes/does it do this already?

**Comment by jrbudda** [comment] 2016-11-22 10:35
Changes have to be made on top of optifine as it so heavily modifies the rendering.

**Closed** 2016-12-02 15:58 UTC
Labels: resolved
