### ISSUE TITLE
Barehanded mining of some blocks broken

### ISSUE THREAD

**Issue by dgallna** [jrbudda/Vivecraft_110#27] opened 2016-07-23 21:27 UTC
Barehanded mining of some blocks (dirt, trees) is broken.  No animation and nothing happens.  Barehanded works on grass and flowers. No problem if using tools.

**Comment by jrbudda** [comment] 2016-07-23 22:49
this is with normal clicking of the trigger? not arm swinging?

**Comment by dgallna** [comment] 2016-07-23 22:57
Correct. Using the right hand trigger per usual mapping of the controllers.  I have reset the options as well as done a clean install fwiw.

**Comment by dgallna** [comment] 2016-07-23 23:49
Update: looks like multiple types of interactions are affected. Just had the same problem with the axe not cutting wood planks (walls) after they have been placed.

**Comment by commandhat** [comment] 2016-07-24 13:01
Duplicate of Bug #21.

**Comment by ArduousWolf** [comment] 2016-07-24 21:49
I am also experiencing this problem.

I lost the ability to mine blocks after returning to a save game in V1R1. At the same time I also lost all sound except the music.

Upon installing V1R2 then sound returned instantly and although I could at first not mine blocks after a few minutes of wandering around I was again able to mine. This lasted about an hour and then suddenly stopped working again. However I had been digger dirt without a tool for that time. I then switched to a pickaxe to mine rocks. It was when I switched back to barehand and dirt that it stopped. I think I broke one or two dirt blocks before it went funny.

I have intalled V2 and the problem persists,

**Comment by jrbudda** [comment] 2016-07-24 22:18
Man I just cant get this one to reproduce... does it only happen with the controllers? like if you switch to seated mode can you mine? Could it be related to using a combination of clicking and roomscale arm swinging to mine? Like maybe turn off 'weapon collision' in the options and see it that fixes it?

I'm sure I can fix it as soon as I can get it to occur on my end.

**Comment by dgallna** [comment] 2016-07-25 02:40
Seated mode and weapon collision changes do not affect it.  Switching from mixed to teleport mode DID seem to fix it temporarily, but it seems to randomly come / go even with a new install, new world, etc. thanks

**Comment by jrbudda** [comment] 2016-07-25 03:16
and when it happens it persists through a restart of the game? or goes away and comes back? and the 'animation' goes away too?

**Comment by dgallna** [comment] 2016-07-25 04:18
Yes it does persist through restarts. The animation also goes away too.

**Comment by jrbudda** [comment] 2016-07-25 04:35
ive been trying and just cant get it to do it. So we will have to experiment... how bout if you bring up the F3 overlay, does it still say the right block you're looking at? The fact it persists though restarts is blowing my mind tbh. Are you using any kind of world rotation?

**Comment by ArduousWolf** [comment] 2016-07-26 15:13
Using the overlay does show the correct block.

**Comment by jrbudda** [comment] 2016-07-28 17:08
I'm still unable to reproduce this. Could someone with this issue try the build below?

It has also been suggested it could be related to window focus/minimized, could that be part of the issue?

[vivecraft-1.10.2-Vivecraft-jrbudda-3-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/388950/vivecraft-1.10.2-Vivecraft-jrbudda-3-installer.exe.zip)

**Comment by dgallna** [comment] 2016-07-28 22:10
I'll try it when can tonight, thanks.

I have the launcher set to close automatically once the game starts.  But Minecraft I twelfth is running full screen so don't know how it could not have focus.

**Comment by ArduousWolf** [comment] 2016-07-28 23:06
I just tried the new build and it seems to have fixed the issue.

However the problem seems to come and go at random, I was able to play all day yesterday and for about an hour today before it hit again halfway through tunnelling down to bedrock. So it may be just a coincidence that I got the ability to mine back after installing it but I hope not.

Will try to play as much as possible and report back if it happens again in the next few days.

**Comment by jrbudda** [comment] 2016-07-28 23:08
thank you. this is the last little thing before the next release. If it's fixed and not related to the window focus thing then I have NO Idea why its fixed, but I'll take it.

**Comment by ArduousWolf** [comment] 2016-07-28 23:35
Yeah I may have spoke to soon, the mining is still working but now I can't interact with the crafting table or furnace at all. I can open chests but the menu showing the contents doesn't open so I can't really use them.

**Comment by jrbudda** [comment] 2016-07-28 23:39
that is likely unrelated, and a good catch. bug from another change I made. thanks

**Comment by ArduousWolf** [comment] 2016-07-28 23:41
Happy to help.

**Comment by jrbudda** [comment] 2016-07-28 23:47
This should do it.

[vivecraft-1.10.2-Vivecraft-jrbudda-3-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/389624/vivecraft-1.10.2-Vivecraft-jrbudda-3-installer.exe.zip)

**Comment by ArduousWolf** [comment] 2016-07-29 00:05
It does. Thank you kindly.

**Comment by jrbudda** [comment] 2016-07-29 00:55
you cant get into the options menu with that one, can you? its alllllways something.

**Comment by ArduousWolf** [comment] 2016-07-29 01:06
I just experienced that, but it corrected itself. It was working fine at first. Then it just happened as I decided to save and quit for the night. No menu but I keep trying to open it and after about 10 tries it did come back up.

There was also another graphical issue that corrected itself just before I could grab a screenshot. Opening chests made the sky colour brighten in the lefty eye only, closing them would return everything to normal.

**Comment by jrbudda** [comment] 2016-07-29 01:14
This should fix the menus. I cannot get the sky thing to occur with chests, if you can pin down the exact circumstances let me know. maybe enchanted items or something?

[vivecraft-1.10.2-Vivecraft-jrbudda-3-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/389697/vivecraft-1.10.2-Vivecraft-jrbudda-3-installer.exe.zip)

**Comment by jrbudda** [comment] 2016-07-29 07:57
released v3. please let me know asap if this crops up again.

**Closed** 2016-07-30 07:53 UTC
Labels: resolved
